UPDATE skills SET name_es='Automatización de flujos de datos y textos',name_en='Data and text workflow automation',description_es='Desarrollo de procesos para transformar documentos y datos, regenerar bases e índices y actualizar la publicación de recursos digitales.',description_en='Development of workflows for transforming documents and data, rebuilding databases and indexes, and updating digital resource publication.' WHERE id=9;
UPDATE skills SET name_es='Análisis de redes',name_en='Network analysis',description_es='Construcción e interpretación de redes para estudiar relaciones entre personajes y estructuras de interacción teatral.',description_en='Construction and interpretation of networks to study character relationships and theatrical interaction structures.' WHERE id=11;
UPDATE skills SET description_es='Diseño de modelos relacionales para representar información bibliográfica y documental, textos y estructuras métricas, conservando relaciones, procedencia y evidencias de atribución.',description_en='Design of relational models for bibliographic and documentary information, texts and metrical structures, preserving relationships, provenance and attribution evidence.' WHERE id=4;
INSERT INTO skills(id,name_es,name_en,description_es,description_en,area,sort_order) VALUES
(15,'Organización y descripción de colecciones digitales','Digital collection organization and description','Organización de documentos, imágenes y testimonios mediante metadatos y relaciones que facilitan su consulta y su contextualización en la investigación.','Organization of documents, images and testimonies through metadata and relationships supporting consultation and research context.','skill_data',45),
(16,'Arquitectura y publicación de recursos digitales','Digital resource architecture and publication','Diseño de la relación entre datos, aplicaciones y archivos, con procesos de actualización y publicación adaptados al mantenimiento del recurso.','Design of relationships between data, applications and files, with update and publication workflows suited to resource maintenance.','skill_development',65),
(17,'Diseño de flujos de edición y revisión','Editing and review workflow design','Diseño de procesos de preparación, validación, revisión y publicación de contenidos, incluidos paneles editoriales y mecanismos de participación revisada.','Design of content preparation, validation, review and publication workflows, including editorial dashboards and reviewed participation.','skill_text',25),
(18,'Diseño de materiales formativos sobre métodos digitales','Digital methods teaching material design','Elaboración de tutoriales, explicaciones y ejercicios que permiten aprender y reproducir procedimientos de codificación textual y análisis de redes.','Development of tutorials, explanations and exercises for learning and reproducing text encoding and network analysis procedures.','skill_development',105),
(19,'Análisis de datos humanísticos','Humanities data analysis','Preparación y análisis de datos de investigación para explorar relaciones, distribuciones y patrones en corpus textuales y bibliográficos.','Preparation and analysis of research data to explore relationships, distributions and patterns in textual and bibliographic corpora.','skill_analysis',108);
INSERT INTO entry_controls(entity_type,entity_id,is_public) VALUES('skills',15,1),('skills',16,1),('skills',17,1),('skills',18,1),('skills',19,1);
INSERT INTO skill_resources(name_es,nature) VALUES('Heurist','platform'),('Jekyll','tool'),('CollectionBuilder','tool'),('Wax','tool'),('SvelteKit','tool'),('Supabase','platform'),('Cloudflare R2','platform');
INSERT INTO skill_resource_links SELECT 4,id FROM skill_resources WHERE name_es='Heurist';
INSERT INTO skill_resource_links SELECT 5,id FROM skill_resources WHERE name_es IN ('Heurist','Supabase');
INSERT INTO skill_resource_links SELECT 15,id FROM skill_resources WHERE name_es IN ('Heurist','CollectionBuilder','Wax');
INSERT INTO skill_resource_links SELECT 16,id FROM skill_resources WHERE name_es IN ('Jekyll','SvelteKit','CollectionBuilder','Cloudflare R2');
INSERT INTO skill_resource_links SELECT 8,id FROM skill_resources WHERE name_es IN ('Jekyll','SvelteKit');
INSERT INTO skill_resource_links SELECT 1,id FROM skill_resources WHERE name_es IN ('CollectionBuilder','Wax');
INSERT INTO skill_resource_links SELECT 17,id FROM skill_resources WHERE name_es IN ('XML-TEI','Supabase');
INSERT INTO skill_resource_links SELECT 9,id FROM skill_resources WHERE name_es IN ('SQLite','Cloudflare R2');
INSERT INTO skill_portfolio_links SELECT 15,slug FROM portfolio_projects WHERE slug='todos-a-una';
INSERT INTO skill_portfolio_links SELECT 16,slug FROM portfolio_projects WHERE slug IN ('todos-a-una','etso-plataforma-web');
INSERT INTO skill_portfolio_links SELECT 17,slug FROM portfolio_projects WHERE slug IN ('todos-a-una','versologia-metadrama','edicion-digital-corpus');
INSERT INTO skill_portfolio_links SELECT 18,slug FROM portfolio_projects WHERE slug='redes-personajes-teatrales';
INSERT INTO skill_portfolio_links SELECT 19,slug FROM portfolio_projects WHERE slug IN ('versologia-metadrama','redes-personajes-teatrales','edicion-digital-corpus');
INSERT INTO skill_evidence_links SELECT 16,entity_type,entity_id FROM entry_controls WHERE entity_type='technical_works' AND entity_id=9;
INSERT INTO skill_evidence_links SELECT 17,entity_type,entity_id FROM entry_controls WHERE entity_type='technical_works' AND entity_id IN (10,11,12);
INSERT INTO skill_evidence_links SELECT 18,e.entity_type,e.entity_id FROM entries e WHERE (e.entity_type='publications' AND e.title_cache LIKE '%redes sociales%') OR (e.entity_type='teaching' AND (e.title_cache LIKE '%XML-TEI%' OR e.title_cache LIKE '%Redes Sociales%'));
INSERT INTO skill_evidence_links SELECT 19,e.entity_type,e.entity_id FROM entries e WHERE e.entity_type='talks' AND (e.title_cache LIKE '%bibliom%' OR e.title_cache LIKE '%Contando palabras%' OR e.title_cache LIKE '%Versología%');
INSERT OR IGNORE INTO skill_evidence_links SELECT 9,entity_type,entity_id FROM entry_controls WHERE entity_type='technical_works' AND entity_id=9;
