import { readFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { createClient } from '@libsql/client';
import { describe, expect, it, vi, beforeEach, afterEach } from 'vitest';
import { parseCv } from './cv-validation';
import type { CvProfile } from '$lib/types/cv';

const connection = vi.hoisted(() => ({ db: null as ReturnType<typeof createClient> | null }));
vi.mock('$lib/server/db', () => ({ get db() { return connection.db; } }));
import { createCv, saveCv, getCv, exportCv, getCvExport, deleteCv, previewCv } from './cvs';

const base = (): Omit<CvProfile, 'id'> => ({ name: 'Archivos', title: 'CV', personName: 'David', affiliation: 'Universidad', website: 'https://example.com/', position: 'Investigador', email: 'david@example.com', language: 'es', version: 1,
  blocks: [{ key: 'a', kind: 'text', title: 'Perfil', body: 'Texto con ñ y edición.', entries: [] },
    { key: 'b', kind: 'entries', title: 'Proyectos', body: '', entries: [{ key: 'e', entityType: 'projects', entityId: 1, commentary: 'Mi aportación' }] }] });

beforeEach(async () => {
  connection.db?.close();
  mkdirSync('tmp', { recursive: true });
  connection.db = createClient({ url: `file:${resolve('tmp', `cv-test-${randomUUID()}.db`).replaceAll('\\', '/')}` });
  await connection.db.executeMultiple(readFileSync('db/migrations/037_saved_cvs.sql', 'utf8'));
  await connection.db.executeMultiple(`CREATE TABLE type_vocab(code TEXT,domain TEXT,label_es TEXT,label_en TEXT,sort_order INTEGER);
    CREATE TABLE events(id INTEGER,title TEXT,date_start TEXT,date_end TEXT,institution TEXT,city TEXT,url TEXT);
    CREATE TABLE entry_controls(entity_type TEXT,entity_id INTEGER,is_public INTEGER);
    CREATE TABLE projects(id INTEGER PRIMARY KEY,title TEXT,institution TEXT,notes_private TEXT,role TEXT,project_code TEXT);
    INSERT INTO projects(id,title,institution,notes_private) VALUES(1,'Archivo','Universidad','NO EXPORTAR');`);
  for (const table of ['publications','talks','teaching','research_stays','education','funding_awards','academic_works','courses','memberships','skills','languages','service_activities']) await connection.db.execute(`CREATE TABLE ${table}(id INTEGER PRIMARY KEY,title TEXT)`);
  await connection.db.executeMultiple(readFileSync('db/migrations/038_cv_header_and_project_roles.sql', 'utf8'));
  await connection.db.executeMultiple(readFileSync('db/migrations/039_cv_affiliation_and_website.sql', 'utf8'));
  await connection.db.executeMultiple(`ALTER TABLE projects ADD COLUMN contribution_es TEXT;
    ALTER TABLE projects ADD COLUMN contribution_en TEXT;
    CREATE TABLE technical_works(id INTEGER PRIMARY KEY,title TEXT,project_id INTEGER,contribution_es TEXT,contribution_en TEXT,context_name TEXT,context_funding_body TEXT,notes_private TEXT);
    CREATE TABLE technical_work_projects(technical_work_id INTEGER,project_id INTEGER);`);
  const migration = readFileSync('db/migrations/040_technical_works_and_project_context.sql','utf8');
  await connection.db.executeMultiple(migration.slice(migration.indexOf('CREATE TABLE cv_block_entries_new'),migration.indexOf('CREATE TABLE documents_new')));
  await connection.db.executeMultiple(`
    ALTER TABLE cv_blocks ADD COLUMN skills_display TEXT NOT NULL DEFAULT 'names';
    ALTER TABLE cv_block_entries ADD COLUMN skill_options TEXT NOT NULL DEFAULT '{"resources":[],"evidence":[]}';
    ALTER TABLE skills ADD COLUMN name_es TEXT;
    ALTER TABLE skills ADD COLUMN name_en TEXT;
    ALTER TABLE skills ADD COLUMN description_es TEXT;
    ALTER TABLE skills ADD COLUMN description_en TEXT;
    ALTER TABLE skills ADD COLUMN area TEXT;
    CREATE TABLE skill_resources(id INTEGER PRIMARY KEY,name_es TEXT,name_en TEXT);
    CREATE TABLE skill_resource_links(skill_id INTEGER,resource_id INTEGER);
    CREATE TABLE skill_evidence_links(skill_id INTEGER,entity_type TEXT,entity_id INTEGER);
    CREATE TABLE skill_portfolio_links(skill_id INTEGER,portfolio_slug TEXT);
    CREATE TABLE portfolio_projects(slug TEXT,title_es TEXT,title_en TEXT,publication_status TEXT,sort_order INTEGER);
    CREATE VIEW entries AS SELECT entity_type,entity_id,'' AS title_cache,'' AS sort_date,is_public AS public FROM entry_controls;
    ALTER TABLE technical_works ADD COLUMN url TEXT;
    ALTER TABLE projects ADD COLUMN url TEXT;
    ALTER TABLE publications ADD COLUMN url TEXT;
    ALTER TABLE talks ADD COLUMN url TEXT;
    ALTER TABLE courses ADD COLUMN url TEXT;
    ALTER TABLE teaching ADD COLUMN url TEXT;
  `);
});
afterEach(() => { connection.db?.close(); connection.db = null; });
describe('CV guardados', () => {
  it('guarda y copia la presentación por apartado sin borrar textos adaptados',async()=>{
    const id=await createCv('Presentación');
    const cv=base();
    cv.blocks[1].skillsDisplay='descriptions';
    cv.blocks[1].entries[0].contributionMode='custom';
    cv.blocks[1].entries[0].contributionText='Texto que debe conservarse';
    await saveCv(id,cv);
    expect((await getCv(id)).blocks[1].skillsDisplay).toBe('descriptions');
    expect((await previewCv(id)).snapshot.blocks[1].skillsDisplay).toBe('descriptions');
    const compact=await getCv(id);compact.blocks[1].skillsDisplay='names';await saveCv(id,compact);
    const copied=await getCv(await createCv('Copia',id));
    expect(copied.blocks[1].skillsDisplay).toBe('names');
    expect(copied.blocks[1].entries[0].contributionText).toBe('Texto que debe conservarse');
    expect(()=>parseCv({...base(),blocks:[{...base().blocks[1],skillsDisplay:'invalid'}]})).toThrow('Presentación');
  });
  it('selecciona recursos y ejemplos de capacidades sin incluirlos por defecto',async()=>{
    await connection.db!.executeMultiple(`
      INSERT INTO skills(id,name_es,description_es) VALUES(1,'Codificación textual','Edición con ñ y XML-TEI');
      INSERT INTO skill_resources(id,name_es) VALUES(1,'XML-TEI'),(2,'CETEIcean');
      INSERT INTO skill_resource_links VALUES(1,1),(1,2);
      INSERT INTO publications(id,title,url) VALUES(1,'Edición','https://example.com/edicion');
      INSERT INTO entry_controls VALUES('publications',1,1);
      INSERT INTO skill_evidence_links VALUES(1,'publications',1);
    `);
    const id=await createCv('Capacidades');
    const cv=base();
    cv.blocks[1].entries=[{key:'skill',entityType:'skills',entityId:1,commentary:''}];
    await saveCv(id,cv);
    const p=(await previewCv(id)).snapshot.blocks[1].entries[0];
    expect(p.presentation).toMatchObject({kind:'skill',resources:[],evidence:[]});
    expect(p.contribution).toBe('Edición con ñ y XML-TEI');
    const adapted=await getCv(id);
    adapted.blocks[1].entries[0].skillOptions={resources:['1'],evidence:['publications:1']};
    adapted.blocks[1].entries[0].contributionMode='custom';
    adapted.blocks[1].entries[0].contributionText='Descripción breve';
    await saveCv(id,adapted);
    const selected=(await previewCv(id)).snapshot.blocks[1].entries[0];
    expect(selected.presentation).toMatchObject({kind:'skill',resources:[{key:'1',label:'XML-TEI'}],evidence:[{key:'publications:1',url:'https://example.com/edicion'}]});
    expect(selected.contribution).toBe('Descripción breve');
  });
  it('hereda, adapta y oculta aportaciones sin alterar originales ni entregas previas', async () => {
    await connection.db!.execute("UPDATE projects SET contribution_es='Edición y modelado de archivos' WHERE id=1");
    const id = await createCv('Aportación');
    await saveCv(id,base());
    const frozenId = await exportCv(id,2);
    await connection.db!.execute("UPDATE projects SET contribution_es='Nueva aportación' WHERE id=1");
    expect((await previewCv(id)).snapshot.blocks[1].entries[0].contribution).toBe('Nueva aportación');
    expect((await getCvExport(id,frozenId)).snapshot.blocks[1].entries[0].contribution).toBe('Edición y modelado de archivos');
    const custom = await getCv(id);
    custom.blocks[1].entries[0].contributionMode='custom';
    custom.blocks[1].entries[0].contributionText='Texto abreviado para esta entrega';
    await saveCv(id,custom);
    expect((await previewCv(id)).snapshot.blocks[1].entries[0].contribution).toBe('Texto abreviado para esta entrega');
    const copied=await getCv(await createCv('Copia adaptada',id));
    expect(copied.blocks[1].entries[0].contributionMode).toBe('custom');
    const hidden=await getCv(id); hidden.blocks[1].entries[0].contributionMode='hidden';
    await saveCv(id,hidden);
    expect((await previewCv(id)).snapshot.blocks[1].entries[0].contribution).toBe('');
    expect((await connection.db!.execute('SELECT contribution_es FROM projects WHERE id=1')).rows[0].contribution_es).toBe('Nueva aportación');
  });
  it('hereda el contexto vinculado y conserva trabajos propios o encargos sin pertenencia académica', async () => {
    await connection.db!.executeMultiple(`INSERT INTO technical_works(id,title,project_id,contribution_es,notes_private) VALUES(1,'Versología',1,'Desarrollo de herramientas','NO EXPORTAR');
      INSERT INTO technical_works(id,title,context_name,context_funding_body) VALUES(2,'Web de una edición','Proyecto de otra persona','Financiación del contexto');
      INSERT INTO technical_works(id,title) VALUES(3,'Herramienta propia');`);
    const cv=base(); cv.blocks[1].entries=[1,2,3].map(entityId=>({key:String(entityId),entityType:'technical_works',entityId,commentary:''}));
    const id=await createCv('Trabajos'); await saveCv(id,cv);
    const preview=(await previewCv(id)).snapshot;
    expect(preview.blocks[1].entries[0].presentation).toMatchObject({kind:'technical',contextName:'Archivo',linkedProjectId:1});
    expect(preview.blocks[1].entries[1].presentation).toMatchObject({contextName:'Proyecto de otra persona',contextFundingBody:'Financiación del contexto'});
    expect(preview.blocks[1].entries[2].presentation).toMatchObject({contextName:''});
    expect(JSON.stringify(preview)).not.toContain('NO EXPORTAR');
    await connection.db!.execute("UPDATE projects SET title='Contexto actualizado' WHERE id=1");
    expect((await previewCv(id)).snapshot.blocks[1].entries[0].presentation).toMatchObject({contextName:'Contexto actualizado'});
  });
  it('guarda orden y comentarios, duplica selecciones y rechaza ediciones concurrentes', async () => {
    const id = await createCv('Archivos');
    await saveCv(id, base());
    const saved = await getCv(id);
    expect(saved.blocks.map(b => b.kind)).toEqual(['text','entries']);
    expect(saved.blocks[1].entries[0].commentary).toBe('Mi aportación');
    await expect(saveCv(id, base())).rejects.toMatchObject({ status: 409 });
    const copied = await getCv(await createCv('Copia', id));
    expect(copied.version).toBe(1);
    expect(copied.blocks[1].entries[0].entityId).toBe(1);
    expect(copied.email).toBe('david@example.com');
    expect(copied.position).toBe('Investigador');
    expect(copied.affiliation).toBe('Universidad');
    expect(copied.website).toBe('https://example.com/');
  });
  it('refleja cambios originales y conserva exportaciones históricas sin notas privadas', async () => {
    const id = await createCv('Archivos');
    await saveCv(id, base());
    const exportId = await exportCv(id, 2);
    await connection.db!.execute("UPDATE projects SET title='Título actualizado' WHERE id=1");
    expect((await previewCv(id)).snapshot.blocks[1].entries[0].title).toBe('Título actualizado');
    const frozen = await getCvExport(id, exportId);
    expect(frozen.snapshot.blocks[1].entries[0].title).toBe('Archivo');
    expect(frozen.snapshot.email).toBe('david@example.com');
    expect(frozen.snapshot.position).toBe('Investigador');
    expect(frozen.snapshot.affiliation).toBe('Universidad');
    expect(frozen.snapshot.website).toBe('https://example.com/');
    expect(JSON.stringify(frozen)).not.toContain('NO EXPORTAR');
    expect(frozen.snapshot.blocks[1].entries[0].presentation).toMatchObject({kind:'project',institution:'Universidad'});
    await connection.db!.execute('DELETE FROM projects WHERE id=1');
    expect((await previewCv(id)).missing).toEqual(['projects:1']);
    await expect(exportCv(id, 2)).rejects.toThrow('ya no existen');
    expect((await getCv(id)).blocks[1].entries).toHaveLength(1);
    await deleteCv(id, 2);
    expect((await connection.db!.execute('SELECT * FROM cv_blocks')).rows).toHaveLength(0);
    expect((await connection.db!.execute('SELECT * FROM cv_block_entries')).rows).toHaveLength(0);
    expect((await connection.db!.execute('SELECT * FROM cv_exports')).rows).toHaveLength(0);
  });
  it('rechaza referencias inyectadas, duplicadas o nuevas inexistentes sin perder contenido', async () => {
    const payload = base();
    payload.blocks[1].entries.push({ ...payload.blocks[1].entries[0] });
    expect(() => parseCv(payload)).toThrow('duplicados');
    const injected = base();
    (injected.blocks[1].entries[0] as {entityType: string}).entityType = 'projects;DROP TABLE projects';
    expect(() => parseCv(injected)).toThrow('Referencia');
    const id = await createCv('Archivos');
    const missing = base(); missing.blocks[1].entries[0].entityId = 999;
    await expect(saveCv(id, missing)).rejects.toThrow('ya no existe');
    expect((await getCv(id)).version).toBe(1);
    expect((await getCv(id)).blocks).toHaveLength(0);
  });
});
